### ISSUE TITLE
Big 3 Upgrade - Q2 2019

### ISSUE THREAD

**Issue by andricDu** [CancerCollaboratory/infrastructure#1]
This issue is an Epic to encapsulate the work required for upgrading Openstack from Rocky to Queens, Updating all compute, controller, storage nodes to ubuntu 18.04, and updating Ceph from Luminous to Mimic. 

### Tasks

- [ ] Stand up song/score test servers for integration testing with Ceph Mimic (#2) 
- [ ] Stand up Billing test server for integration testing with OpenStack Rocky (#3)

**Comment by jmimico** [comment]
Current upgrade schedule:
ASAP Ceph Luminous to Ceph Mimic upgrade (no public announcement because should not be user impacting)
Tuesday-Wednesday, April 23-24 (Ubuntu 16.04 to 18.04 migration)
Tuesday-Wednesday, May 28-29 (OpenStack Rocky upgrade)

**Comment by andricDu** [comment]
Closing this as it is finished.
